spring.application.name=BattleshipServerApp
server.port=8080

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:battleship_db}
spring.datasource.username=${DB_USER:admin}
spring.datasource.password=${DB_PASSWORD:1111}

spring.jpa.hibernate.ddl-auto=update

game.rules.count-ships=21